version: '3'
###docker-compose -f docker-compose.yml up --build
services:
  worldofgame-service:
    build: .
    image: gadifer/wog:v1
    volumes:
      - /training/devops/templates/Scores.html:/training/devops/templates/Scores.html
      - /training/devops/scores.txt:/training/devops/scores.txt
      - /training/devops/oldscore.txt:/training/devops/oldscore.txt
    ports:
      - 5000:5000
